# Railway Deployment Configuration
# Place this file in the root of your backend directory

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[env]
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"
PORT = "8000"
